title: Jason Starr # your name (or website title) here
logo: "/images/jason_profile@2x.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  <a href="https://www.linkedin.com/in/jason-starr-tech/">View My LinkedIn Profile</a> 
  
theme: port-theme
google_analytics: G-6JX7VSC10F # your Google Analytics tracking ID here
